services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cr3t
      - POSTGRES_USER=carro_usr
      - POSTGRES_DB=carro
