name: Playwright Tests
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      # Setting environment variables with the values of repository variables
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ vars.PORT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Display Environment Variables
        run: |
          echo "NODE_ENV: ${{ env.NODE_ENV }}"
          echo "PORT: ${{ env.PORT }}"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start Node App
        run: npm start &
      - name: Wait for App to Start
        run: sleep 10s
      - name: Run Playwright tests
        run: npx playwright test
      - name: Stop Node App
        run: pkill -f "npm start"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
